spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  application:
    name: shopping-cart-high-concurrency
