{
 "title": "Spring Boot HTTP",
 "description": "Spring Boot (Micrometer) with HTTP requests.",
 "tags": [
  "prometheus",
  "spring-boot",
  "micrometer",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_max,instance)"
    }
   },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values(http_server_requests_seconds_max{instance=~\"$instance\"},uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${uri}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "uri" },
  {
   "title": "HTTP Response Time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket{uri=~\"$uri\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=~\"$uri\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "95th percentil",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{uri=~\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentil",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{uri=~\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}